### ISSUE TITLE
I want to contribute but I wanna know I have your back

### ISSUE THREAD

**Issue by thednp** [mgreter/sass.link.js#4]
I found your repository yesterday and I haven't even started working on it yet, but still I believe it can be something to do with it.

Currently I'm interested in:
* updating this codebase to latest `sass.js` 2019 version
* give it the ability to resolve deep paths and parallel paths, EG `../../anotherVendor/scss/vendor.scss`
* give it the ability to work outside the demo markup, I mean compile and `writeFile` of our own

In the end I need to know a couple of things, for instance: 
* what exactly did you change in the original Sass and Sass.worker?
* what exactly is your contribution to the original source? I need to know that to be able to update the Sass code base
* can this work with absolute path sources?

What do you say?

**Comment by mgreter** [comment]
This project is up for grabs for anyone who would like to take it further.
I don't really consider this route to be viable for any decent workflow though.
As a main developer of the underlying LibSass this was/is merely an experiment.
I believe the future of this route will more be in the way of WebAssembly.
